name: flutter_skeleton
description: Flutter skeleton screen for Android and iOS. Support List, Card and Card-List style. Support light and dark theme.
version: 0.1.0+1
author: Dylan Wu <dylanwuzh@gmail.com>
homepage: https://github.com/wuzhendev/flutter_skeleton

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=0.4.1 <2.0.0"
